import ts, { factory } from "typescript";


export const createCatDogStatements = () =>
  [
    factory.createVariableStatement(
      undefined,
      factory.createVariableDeclarationList(
        [factory.createVariableDeclaration(
          factory.createIdentifier("cloud"),
          undefined,
          factory.createTypeLiteralNode([factory.createPropertySignature(
            undefined,
            factory.createIdentifier("CreateBucket"),
            undefined,
            factory.createFunctionTypeNode(
              [factory.createTypeParameterDeclaration(
                undefined,
                factory.createIdentifier("T"),
                undefined,
                undefined
              )],
              [],
              factory.createTypeReferenceNode(
                factory.createIdentifier("Bucket"),
                [factory.createTypeReferenceNode(
                  factory.createIdentifier("T"),
                  undefined
                )]
              )
            )
          )]),
          factory.createAsExpression(
            factory.createObjectLiteralExpression(
              [],
              false
            ),
            factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword)
          )
        )],
        ts.NodeFlags.Const
      )
    ),
    factory.createInterfaceDeclaration(
      undefined,
      factory.createIdentifier("Bucket"),
      [factory.createTypeParameterDeclaration(
        undefined,
        factory.createIdentifier("T"),
        undefined,
        undefined
      )],
      undefined,
      [factory.createMethodSignature(
        undefined,
        factory.createIdentifier("on_object_created"),
        undefined,
        undefined,
        [factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier("handler"),
          undefined,
          factory.createFunctionTypeNode(
            undefined,
            [
              factory.createParameterDeclaration(
                undefined,
                undefined,
                factory.createIdentifier("key"),
                undefined,
                factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
                undefined
              ),
              factory.createParameterDeclaration(
                undefined,
                undefined,
                factory.createIdentifier("obj"),
                undefined,
                factory.createTypeReferenceNode(
                  factory.createIdentifier("T"),
                  undefined
                ),
                undefined
              )
            ],
            factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword)
          ),
          undefined
        )],
        undefined
      )]
    ),
    factory.createEnumDeclaration(
      undefined,
      factory.createIdentifier("Kind"),
      [
        factory.createEnumMember(
          factory.createIdentifier("Cat"),
          undefined
        ),
        factory.createEnumMember(
          factory.createIdentifier("Dog"),
          undefined
        )
      ]
    ),
    factory.createInterfaceDeclaration(
      undefined,
      factory.createIdentifier("Cat"),
      undefined,
      undefined,
      [
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("kind"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createQualifiedName(
              factory.createIdentifier("Kind"),
              factory.createIdentifier("Cat")
            ),
            undefined
          )
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("catName"),
          undefined,
          factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("age"),
          undefined,
          factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword)
        )
      ]
    ),
    factory.createInterfaceDeclaration(
      undefined,
      factory.createIdentifier("Dog"),
      undefined,
      undefined,
      [
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("kind"),
          undefined,
          factory.createTypeReferenceNode(
            factory.createQualifiedName(
              factory.createIdentifier("Kind"),
              factory.createIdentifier("Dog")
            ),
            undefined
          )
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("dogName"),
          undefined,
          factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword)
        ),
        factory.createPropertySignature(
          undefined,
          factory.createIdentifier("age"),
          undefined,
          factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword)
        )
      ]
    ),
    factory.createVariableStatement(
      undefined,
      factory.createVariableDeclarationList(
        [factory.createVariableDeclaration(
          factory.createIdentifier("bucket"),
          undefined,
          undefined,
          factory.createCallExpression(
            factory.createPropertyAccessExpression(
              factory.createIdentifier("cloud"),
              factory.createIdentifier("CreateBucket")
            ),
            [factory.createUnionTypeNode([
              factory.createTypeReferenceNode(
                factory.createIdentifier("Cat"),
                undefined
              ),
              factory.createTypeReferenceNode(
                factory.createIdentifier("Dog"),
                undefined
              )
            ])],
            []
          )
        )],
        ts.NodeFlags.Const
      )
    ),
    factory.createExpressionStatement(factory.createCallExpression(
      factory.createPropertyAccessExpression(
        factory.createIdentifier("bucket"),
        factory.createIdentifier("on_object_created")
      ),
      undefined,
      [factory.createArrowFunction(
        undefined,
        undefined,
        [
          factory.createParameterDeclaration(
            undefined,
            undefined,
            factory.createIdentifier("_key"),
            undefined,
            undefined,
            undefined
          ),
          factory.createParameterDeclaration(
            undefined,
            undefined,
            factory.createIdentifier("obj"),
            undefined,
            undefined,
            undefined
          )
        ],
        undefined,
        factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
        factory.createBlock(
          [
            factory.createVariableStatement(
              undefined,
              factory.createVariableDeclarationList(
                [factory.createVariableDeclaration(
                  factory.createIdentifier("catName_0"),
                  undefined,
                  undefined,
                  factory.createPropertyAccessExpression(
                    factory.createIdentifier("obj"),
                    factory.createIdentifier("catName")
                  )
                )],
                ts.NodeFlags.Const
              )
            ),
            factory.createVariableStatement(
              undefined,
              factory.createVariableDeclarationList(
                [factory.createVariableDeclaration(
                  factory.createIdentifier("dogName_0"),
                  undefined,
                  undefined,
                  factory.createPropertyAccessExpression(
                    factory.createIdentifier("obj"),
                    factory.createIdentifier("dogName")
                  )
                )],
                ts.NodeFlags.Const
              )
            ),
            factory.createVariableStatement(
              undefined,
              factory.createVariableDeclarationList(
                [factory.createVariableDeclaration(
                  factory.createIdentifier("age_0"),
                  undefined,
                  undefined,
                  factory.createPropertyAccessExpression(
                    factory.createIdentifier("obj"),
                    factory.createIdentifier("age")
                  )
                )],
                ts.NodeFlags.Const
              )
            ),
            factory.createIfStatement(
              factory.createBinaryExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier("obj"),
                  factory.createIdentifier("kind")
                ),
                factory.createToken(ts.SyntaxKind.EqualsEqualsEqualsToken),
                factory.createPropertyAccessExpression(
                  factory.createIdentifier("Kind"),
                  factory.createIdentifier("Cat")
                )
              ),
              factory.createBlock(
                [
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [factory.createVariableDeclaration(
                        factory.createIdentifier("catName_1"),
                        undefined,
                        undefined,
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("obj"),
                          factory.createIdentifier("catName")
                        )
                      )],
                      ts.NodeFlags.Const
                    )
                  ),
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [factory.createVariableDeclaration(
                        factory.createIdentifier("dogName_1"),
                        undefined,
                        undefined,
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("obj"),
                          factory.createIdentifier("dogName")
                        )
                      )],
                      ts.NodeFlags.Const
                    )
                  ),
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [factory.createVariableDeclaration(
                        factory.createIdentifier("age_1"),
                        undefined,
                        undefined,
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("obj"),
                          factory.createIdentifier("age")
                        )
                      )],
                      ts.NodeFlags.Const
                    )
                  )
                ],
                true
              ),
              factory.createBlock(
                [
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [factory.createVariableDeclaration(
                        factory.createIdentifier("catName_2"),
                        undefined,
                        undefined,
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("obj"),
                          factory.createIdentifier("catName")
                        )
                      )],
                      ts.NodeFlags.Const
                    )
                  ),
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [factory.createVariableDeclaration(
                        factory.createIdentifier("dogName_2"),
                        undefined,
                        undefined,
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("obj"),
                          factory.createIdentifier("dogName")
                        )
                      )],
                      ts.NodeFlags.Const
                    )
                  ),
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [factory.createVariableDeclaration(
                        factory.createIdentifier("age_2"),
                        undefined,
                        undefined,
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier("obj"),
                          factory.createIdentifier("age")
                        )
                      )],
                      ts.NodeFlags.Const
                    )
                  )
                ],
                true
              )
            )
          ],
          true
        )
      )]
    ))
  ];
